### PR TITLE
added FIP webradio

### PR DESCRIPTION
**Pull request by 5AMsan**
Added 6 web radio streams metadatas URLs to France/index.js

### CODE REVIEW

**Comment by dest4** [comment]
Great contribution, thanks. Will review it ASAP

**Comment by 5AMsan** [comment]
You're welcome. Here are my tests :
```
[2019-04-04T08:39:05.264Z] info meta:   {"data":{"artist":"IBRAHIM MAALOUF","title":"SENSUALITY","cover":"https://cdn.radiofrance.fr/s3/cruiser-production/2016/12/986d4b39-9eb3-4c55-be47-4e2411466f77/400x400_rf_omm_0000986670_dnc.0034744102.jpg"}}

samsan@COMM-DEV00:~/webradio-metadata$ node index.js France "FIP Groove"
[2019-04-04T08:39:11.002Z] info meta:   {"data":{"artist":"CURTIS HARDING","title":"IT S NOT OVER","cover":"https://cdn.radiofrance.fr/s3/cruiser-production/2018/06/b4e20848-67c6-4c62-81a5-2d95a89232f1/400x400_rf_omm_0001650915_dnc.0077397143.jpg"}}

samsan@COMM-DEV00:~/webradio-metadata$ node index.js France "FIP Rock"
[2019-04-04T08:39:15.714Z] info meta:   {"data":{"artist":"THE EX","title":"SOON ALL CITIES","cover":"https://cdn.radiofrance.fr/s3/cruiser-production/2018/04/059d95fa-b075-4d01-be2e-8816c53d4314/400x400_rf_omm_0001641546_dnc.0076495109.jpg"}}

samsan@COMM-DEV00:~/webradio-metadata$ node index.js France "FIP Monde"
[2019-04-04T08:39:22.405Z] info meta:   {"data":{"title":"La vie en Bleu France Bleu Paris - Corentine Feltz"}}

samsan@COMM-DEV00:~/webradio-metadata$ node index.js France "FIP Reggae"
[2019-04-04T08:39:26.993Z] info meta:   {"data":{"artist":"KING JAMMY","title":"KING JAMMY YOU HIT ME","cover":"https://cdn.radiofrance.fr/s3/cruiser-production/2017/01/7c76a896-1cd7-4a58-98bb-e2e9a134d7e0/400x400_rf_omm_0000168640_dnc.0058024775.jpg"}}

samsan@COMM-DEV00:~/webradio-metadata$ node index.js France "FIP Nouveaute"
[2019-04-04T08:39:32.791Z] info meta:   {"data":{"artist":"AZIZ SAHMAOUI & UNIVERSITY OF GNAWA","title":"SOUDANI YA YEMMA","cover":"https://cdn.radiofrance.fr/s3/cruiser-production/2019/01/b5e5d78b-e175-4eef-89f0-48a24944f81a/400x400_b5e5d78b-e175-4eef-89f0-48a24944f81a.jpg"}}

samsan@COMM-DEV00:~/webradio-metadata$ node index.js France "FIP Electro"
[2019-04-04T08:39:43.956Z] info meta:   {"data":{"artist":"MARCAS","title":"THE LOOKING GLASS","cover":"https://cdn.radiofrance.fr/s3/cruiser-production/2016/11/7a618366-88fe-4963-bdf2-b8d8a086cbc0/400x400_rf_omm_0001394062_dnc.0062445172.jpg"}}
```

**Comment by dest4** [comment]
The names of the radios you used, such as `FIP Nouveaute`, do not match the names available in the [radio-browser wiki](http://www.radio-browser.info/gui/#!/byname/FIP).

Please fix that

**Comment by dest4** [comment]
Edited and merged your contribution, now FIP webradios are available for scraping :tada:

**Pull request merged**
